# Copyright 2021 Camptocamp SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html)

from datetime import datetime

from odoo import api, models


class SaleOrder(models.Model):
    _inherit = "sale.order"

    @api.model
    def cron_generate_weekly_invoices(self):
        """Cron called daily to check if weekly invoicing needs to be done."""
        company_ids = self._company_weekly_invoicing_today()
        if company_ids:
            self.generate_weekly_invoices(company_ids)

    @api.model
    def generate_weekly_invoices(self, companies=None):
        """Generate weekly invoices for customers who require that mode.

        Invoices will be generated by other jobs split for different customer
        and different payment term.
        """

        saleorder_groups = self.generate_invoices(companies=companies, mode="weekly")

        companies.write({"invoicing_mode_weekly_last_execution": datetime.now()})
        return saleorder_groups

    @api.model
    def _company_weekly_invoicing_today(self):
        """Get company ids for which today is weekly invoicing day."""
        today = datetime.now()
        domain = [
            "|",
            ("invoicing_mode_weekly_last_execution", "<", today),
            ("invoicing_mode_weekly_last_execution", "=", False),
            ("invoicing_mode_weekly_day_todo", "=", today.weekday()),
        ]
        return self.env["res.company"].search(domain)
