# Copyright 2022 manaTec GmbH
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html)

from datetime import datetime

from odoo import api, models


class SaleOrder(models.Model):
    _inherit = "sale.order"

    @api.model
    def cron_generate_daily_invoices(self):
        """Cron called daily to check if daily invoicing needs to be done."""
        company_ids = self._company_daily_invoicing()
        if company_ids:
            self.generate_daily_invoices(company_ids)

    @api.model
    def generate_daily_invoices(self, companies=None):
        """Generate daily invoices for customers who require that mode.

        Invoices will be generated by other jobs split for different customer
        and different payment term.
        """

        saleorder_groups = self.generate_invoices(companies=companies, mode="daily")

        companies.write({"daily_invoicing_mode_last_execution": datetime.now()})
        return saleorder_groups

    @api.model
    def _company_daily_invoicing(self):
        """Get company ids for which today is daily invoicing day."""
        today = datetime.now()
        domain = [
            "|",
            ("daily_invoicing_mode_last_execution", "<", today),
            ("daily_invoicing_mode_last_execution", "=", False),
        ]
        return self.env["res.company"].search(domain)
