from odoo import fields, models


class ResCompany(models.Model):
    _inherit = "res.company"

    self_invoice_prefix = fields.Char(
        string="Default Self Billing prefix",
        help="Self Billing prefix for Bills generated by this company",
    )

    self_invoice_extra_infos = fields.Text(
        help="Additional information that will appear in the footer "
        "of all self-billing vendor bills "
        "emitted by this company.",
        translate=True,
    )
