from odoo import fields, models


class ResCompany(models.Model):
    _inherit = "res.company"

    self_invoice_auto_ref = fields.Boolean(
        string="Generate reference with specific sequence for self-billing",
        help="If checked, a specific sequence will be used to generate "
        "the Self-Bill Invoice reference when validating a vendor Bill.",
        default=False,
    )
    self_invoice_prefix = fields.Char(
        string="Default Self Billing prefix",
        help="Self Billing prefix for Bills generated by this company",
    )
